### PR TITLE
upgrade ex_doc version

### PR DESCRIPTION
**Pull request by peaceful-james**

### CODE REVIEW

**Comment by LostKobrakai** [comment]
Just wondering, what‘s the reason for doing this update?

**Comment by peaceful-james** [comment]
When I try to use this lib, it won't install due to many other libs using v0.23

**Comment by LostKobrakai** [comment]
Ah good to know. I've missed limiting `:ex_doc` to `:dev`. It should not even require it when used as a dependency.

**Comment by LostKobrakai** [comment]
Just published v0.1.3 with a bunch more improvements

**Pull request merged**
